version: '3'
services:
  app:
    build:
      context: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: mysql-user
      DB_PASSWORD: mysql-password-insecure
      DB_DATABASE: mysql-database
    ports:
      - "8000:8000"

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root-password-insecure
      MYSQL_DATABASE: mysql-database
      MYSQL_USER: mysql-user
      MYSQL_PASSWORD: mysql-password-insecure
    ports:
      - "3306:3306"
